language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 5.6
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.0
  - php: 7.1
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_Statuschange
  - secure: jmGpzDbtpMYqyxTMzVaG8hKQwBq2mmpbscskg6Gmz0X5kjpB/UrxOG+k6Nnh/gKl/O6J9Pehek8wa5y53+k4s4dYcAdE2QPoP9ZU/OyvKkBM5PkUXAUemsqD68M6i87vmoU89J33ldgi1Az6xf2Qs8//3sfir18M6zky5jfMgSCj+pR73XmzH3Qm7B8efUBN8m9jixAAn6I2LWK7MDuMf9mbp5Wgwe+H8lcBBsSpODScuBxHNGp9i3aG1hdfnfkcm1ecU89OFTG4ksFwhE/mQL3UmXKYXsvKwLt5VOavGQ3C0sC/EeYtImUArelhN4nzW6OXMzi+RQjWWg0kwXdQ8ZyhQF384DcO4FXzlH7dTVkhjUPbeguVz29vzRKWUWss40WJ1Lqoa2cQbkFhRifUoDjdp9Cv7WMZYTmAcJ7k7IdT/mccFXqethe8PVVi4DqE441acb90efHVASoICY7GbV9oZKx9103GmRgfrDqzH3PZFu1Pg/PYt3fRhnsoi/Y5sHfEfJB4qnKKeOAIy9qgkk2VVeoMS/HFP3d93pBgxzkZPMogaukUq9qccFjL1HXzy1d98OnVXWjY1KTZFDEshkjqHubh5tionqzKReaZ0eYCkbAFXSZDxs0h4GqMaP9vno4Fl4zzVEp29R7XXY1zc8yCsIG+N4N2womfOdCKMcA=
  - secure: p808/gML/OqF8UemXXWtPvwpPJqIybTGa+pYY868S5CFtDnEUK41eBgzf8L4/fgxR+43j+exdyXp4Y9ATkaTS97HYdiLzJQcpkMy+Hfm0jxDs+BO+RJ+OIYOoaULqBhb++ms6BFcFiPd9iiEXSN6CmXUlBFRoAo7GgnNam33fp8joakiVCfc3GDST5VmwGlxFEimFcSWC+JEUi+kFBTe9HokmauPCNsstLXY1bac/TaSnPWKONC/PjQpabERukr7v4nSD10gibGfOTW6qYqdHCqnY5SDOC+iNuWXxUl8ZysU68wJSjen8yaDRy6DPOrxrMf9cVlJeRhDVBjg49yeTlw/lp7aVs4x++DSQC4Xzq52dmQCISBDtIQKc+YveIfLNLHYwWOKYItIss0HzZErAvncwPKbm1puke3SE8mdJpfHH9D/t48E1piujfKWigy4CvJPiWtjkDu4iRonRitxI6+wndDjNhXNhvoMoAHOc4vSPCT3JYXWaC+NhrQqZNC0f0yEBfHdmYOsZJFtAC6OsY2EW5SAydY9nbjXoX7S272b/13FMTTO3iwlWSMmkQpLz5hD3iL4WEQgzFywUbW3d7FRoP/ESYfHfYnk27EnmpU1Zsdz9ILkdAv1vhyHpTAHFJWDEKMt28oy4wQUNr3qVgalN3Z2c1VnKCzmF5DQ5IU=
  - secure: jlrBDApG/nRALETHWq5iqfVuUI9exYpUl39EQwjgLXaasuTWKluT0kMd+UuEj6nAvtiu0sWvO5bjVZPo5DTF0oSQbSWS0ZcoEeV7YUapPCxilPVMgxv/WybCsg4CETNkcvejFOe4/gcuPr5540BqDXnKisLbStha/oWqjHDqeSWZxnjzDpZGkTOnxws6O58kG2vVyFk9nycGQgvbSJufXZJY/QBVeeLG0Mbz5okzsfNThJt3YlBitno9qGKd0fyOx2rXCNBqNV1tqo3ZKzhe7IJiuOl/Sv9+sDnNcLZYbKwZ+wCOw96sLRK1MPJM3gONY0X2hrnPpT0wBlevB4VsHygxKE7IZhmAXPjZ/v3wmPsHArgHAqMWxSE+CTp+bpbrM9tLOzWoUXCKw944fDtg9e91OvaNFgzw0CJmdqmwHhlorK8a920xaW/W3DEl1jcyTwcS0k8dFoKGb7KwTq8YfPHLf+4uBD2h1xohRN37l+CgakROaBdvqGRf2kepPoz4nsAM+jUdNYsBOBz6+7tcWGEFwOS0qtjvR6tJT1bN/WGB/7swmBP5/1qRb+uf1fI2hu8TiJqWtLKKer3CFZiFfgpJ3r6th6YpqeIe9Z8JKyKweyC8F/lSYhdp7MAp+YxBiVlsPkzk4tj3bnU5VFe2kKVnbzvB4EH1QSxclPcnl4o=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.7
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/dev/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/dev/script.sh |
  bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: 00Q2Gy1UDPUHkZzZdkBuqajn1W+eGs994931uiT6SyHHd97Tg8NXZHnhtb2t9HZDhBIi6i0qXOATDHX2DEtrl5qyiXTiGcwaQn0gc7PvGb+8MvotEHEUSHwIrR4H5JkDLzmLf4m9IB4WBCRrmBUAlQxmUHQq+wiRXUb34yDTO1TtmwYiwgLyLJ91Q7jUmZC/A1OXjQcen1IM2L8c4mRpRFQV1aHwk5MQnLZBxL/jaND0JSyXjR5/W3QXLOHAHZLc9+9z0KIPHyDyFpGxfJhNg6zNQ/vlU7Ww7h5/H4yIKoMAiIV7HLJZ9/8M2C+wBEykVOLrJm+P5MOyq6Sy/N4uWu/R0gUy9fg5rbJvHMBPbHsH5moF+sYJj0Re1kUkP6ZIbQkSoigwjYnND0ABENkoDSae9cCIIeyho/RwwtGK4qRtMZXFjA9EcK2VmaUwxLbRejgpX+PNES+z6SSJL26pVAdHKsZDzZPljV5IBkFNGQF4QjifKGEpuDFe8XMJpmRIyKbGk+Qg/qefeofe7iNpHdJ5cUnAB01Tp9VZYTTTxUtbdKDSuaqy1AGYoMMnFKcGAvEEbzVR5HxN/rYadCeuOXasYFjmK8PGjjrxki49ZpUEm+s9A3jcYritZJh/HZTCYRgYppqyWV0RVXHQlXkMXnUiwhNn5IaF7AKm/4v8stg=
notifications:
  slack:
    secure: Td52o2CtiaqQz+WMF7+oeiZplHRgzXmZCSUHvztRlYYWZucwOfWTEefAqYoUlzj1lkEZgitAPl/2tcKi5l7I9Axc9QMbJCuPeeZkIrdiFI5opxgqKV7eJ3ennwyIqM5wmW4WL6QjKXEQy8Rs4m4n3/NcfoxcLBCMxJb89PgSukospAkcym8RWqUEeeif+AXVGls/XrChDECwJ1nBjUf4kicLm3HtWkHJRgtTl4H+eoUIld/Ti6gj763z4n3foefGb36aNqpBgz1AFjZeMf9n6pJfaht/JhdBvkw5i/Ss2RXIuITkYzyDyV0q2m8C2IPlbNWmmaHlWG1fAvBuNh13sNkR99eP45tXQAw1AH62pqf9wQ+CduvBJ7gRPUyECuavH3gEf6BaL9HHjuqDARZNlPDW0PKLge0mKg/pXfcGwrWcm4GrdW5/lzHfSdNrHxc6YIbg2r9tr/B7LfmLX7n4RPGTiykgDRmUjxIYagcov+B9SrhGl8gkxxdR6x/CtbjHRO7oGZrIm0K0seoX++iAfIUQQCNPI/Xa/wPcjuN0R68TfUhL9PmEwSomen7Fpi0PZvJrJdEVhhPW9FkJGJh3OkL/epGa4DOPq27EOPOPxClIRjqoFkfbuo/WQ0548uLtZaGg2DZPEhU+K1cXYetnRRc9uOKdtOki4EnL0kYy9Nc=
