language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_Statuschange
  - secure: lw/fyjkZ17gl0eAoCbacHKwehlE34kYgaqmnHrA7B7J/qsYaiaisSLtFd3otj9spLJjGbAtEJfPKLUZYTb7P/gEkaj5ADgBmSLqlDrcuDLIWeKK7E9jQi6ZI/5bxOrmJBNK2R4ObqRzU5uqe9ZiG/EfWZlAgcKjc1wm1zP349sZqvK9jJo/IKXzw0SmHScku+JIqyxnu1DxWAFHHfHVBut1CGzZwCBn2vcmke9xqAIFxg41Zk5okMOsb1iZWl13OisUZ0ZQkwyqpeltXyyPohotk9ler8aeQLAV1TELf82x9PdPWaZ00bO1sPI1uUeRgZ6RL4twhw211Te3/t4ws5IKEPM/a5r3IXciDl8raCcdz//xjkswdsq0b1uAIG3KnRc2wFsKPbBf0Zi4QwY+oU2uhTuxtc4/EqSsjlwwBLOrftCF5km3t1VQWrOv1jFk8I5Xhn+7Nf76fmQl59ldXkn3NVaZKuv1DX94McPfHCSzUN+QzjWKfeanTogNAQs2QA0gLSfXpZI9+ZtKgD5loPzWozGB8IGXxk8oNvqSNzPx6QWK2X7X81nEK+YuMINUomc0rqmFu+/RR5GZUyaAz3BWVvGFlcFsEM2yjJOB3Tkwmz6y5DA7XKEuiWpuVbmzS66Mh/+A6euSMl4oylbMv/Qddafthpw6Ocrvz+fyWSgo=
  - secure: TC2cYLYDB1S7fN4v2BvsrvcLP9oPZLNma/9B/al7CVpgWVhDzJdm8s0VZXHD0SPPiyqcgFX1npSm3GB3MVfK0ixobKGIViQwS2zNQO4R8WISCLIg3reB1COezSM1Bd4QQLMg8mloBw3JjAO+dh4VN65H2czlFOvboNIFcjS20bAbUvYB+BxoPycpmqPogrcZDv3yfBXln+QGZz2lmJuFibWPBuCBUjqWvEaLgZz0nCnHKvd50o3zDvoTReVg6rvw2gVYqTpGMXqtg3cpJsldiX+SQ8O6QDC71cAk+9jRG5vyj/onV9IAk/5cZJChJiDJRTHvF6drQSd0v6VSZXCmWgw9a/atruf7oOD4fRP52VHTdr74DwirTE6UPRCRE9saxDYTM9Ocwdq5R/YgePuz6/Esg+ZIE6aOMr6qBaeiq7AOSzSZuvNFQAKCdXHPagw36u1zyQhEHmtVzB+vHUxKZNRsBERQpWHzMPjmJDkSjYQhMz6+pT6vHY5kQCYZutWXWAA0jRRkfcSxGqdrGDf2kZpYausZ5iMRGlUM54dD7mgX3CKKyRIp+bkaC0KEiNMrxPhw5pWE+D2RxmPgyUaJAjNpLaNlHpF162gVQYU/Dtu6SkIPCXyEs47xE8okcbb31rGbImheDYPs1Ur73AptU73p5wC9pkNJSi557eFu1Y0=
  - secure: eS8XwTGa4q/L9KyNhQFglq1Ceo9X0d8cVtEIDqIlRi6E5tjv+2gtwcc4ZfMptGi4xdhzz/ApgOhQGCY+0VtUXpT6XCn5S6O4Uo6YgfVnOzYhuzZ5E9MJ8TpWjYMUf/Vav9PynRhwD+HD49PksNS8XsqSrkiv6tIQSrE7vnVUg2vFe9aheqjIOstimLLTViiab3WKRiWf8WfJgBcQcJi/Mmu+dKO5VeqCKD0z9YsY2Ji4DPvGEI+orNEdUMngoyK4UPMg9M1BIMl5QXHBeBOCu16cMk+mjYiVcUMwCpLFWb7JoDuoUPP3LeFrvM5xqXINnatNTjETPnc0vPZdFj4X9UgO1KvFZerRCX72LxE5JYNaH32DQZgimOR1+WkPvgZQQ7aqQzunw6rFXYzAEiZZFxFOvw/CxiJERJ5GJobvkW9yb9aQ+cc29Qt5F+yoD9hKCnDdotmECDxUJUXl1mkzcAgHSHH+Uw535YxiPUttu+9qxu5ZfLChH9oPoWO2qzlksO8yA96wqIPGoYk8wyscf5XhlsozIEbTS6dxvCHiQz+z67EDyQnTHmyY7BInyTaf2bLzfj7n781vJmbLZJY9GLhYJXUDNYA5iv6KIDoSFgnv8RkB9ppZkN77EIqf+2iwrWZpNtK7qsvRJyhDN8NCesFe8aBmqiY3kkJ8Q58U384=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.10
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: jf0Pz3XOXCeb1QRbf8OkBmObGPvh6b9F1chm0iGjgnjBhvWcQC3Ho6JEh1VyEAMxJQbdG14jOxUKtd0TpXPj6fOTn3UXOJuzZGMubLpwzaYxIyM4JbOZDw2wEffrSTkrxf6SXb0PrxkjWGPxsntxTDzfQ7kDsBF1oLJLJfHou8MB87xsKl/6P9G3bBgy0z8h1IAA8xd+O5z4ShOOjTN292PXOljs/oIDlluF9NDw/B+/70//os3gaTXSB9uR3ZQVGmrlrs2Oo3shEgn30DdBY0W0+NcPTS8xqQyP9hhXoQRaO0jIAuFcg+QDGJO0BtAoISodxxcgUToOnBKlZ5ySWOaxWYG6d2nCMHsnmvXnDKa/OQtYh9/AxiZc3WX5bOA1cieOpegoVncrAgkyabqLSgNOxfwMAPCqyFfJiOHorlrR1m9S1n6UPnrj1V981ujonk2QKLA6tUsTzCzpMmcDCYnniX4cPwnvRoQLHsRl65WOY7QBCpmfFE9q39HJb3O2ifIh5xv8GGiw5o59mhe9RqOMLaFJaEUoMPVoKIlA54Zozmpdj0KXSbL3f0B35G/7HmDEff1aH/Ip6YZCwCl6kA2ru/SgPvKvUCMTdJ+mg/8JxgbsAUMnbYfukGGDtaEyfqSIV691iKxJKhLY5xaUiQVWzPLnSTd4RiOR3TfL2O8=
notifications:
  slack:
    secure: v0MZeuAjVFXrRjz0SfM2EVfGHllWFSDWeqtCTQdQJ7sun0/FTF2RnZo+E6N/vx+w6ZEGsqV9m2/GPUVWPFOeEN6yoQwy2oVjxs2qMZtj30rzgWD0HKDMKe8Hb3R3DQA5yqDvUeo+bnfyGfHWlJEKshpK5kUyjQhdvBLc84alE2hHYds+iySkqMTKcIIzPZ8052nxxquxBUE4zb87yudkCmFzmHTJd5Lhunqea63l7hN730siCwN5/hPMQcgqgef81hIZuTYOvGDKK3Vo8LtsVRP+EpIxb4BrDeaJYA+vS2NkXWwCkEAsP9+X8JOvB3YtBHQkeUWESt8QlycNXdiFpOCNmBAe/EBS6QjSlIpqkhZwcry515YlgAiaiTxpzhPP3U+bTxq6xF3c+kJdgFg105Z5iUCHi26EWnZdNfSmHkNEUfLG04KK7S0NG2ujGzQBZd0c2NePd4arEGuGrhP02oyiiXdp/x3Ry2+BwXI0OFRW+Sgk6DL/KdC8iAbojsYVdyYzYrB7+uz6EjskXzG6K7nrcNVwAkCKiyTttTHAs2Iwfvi263IlFprh4izGAgZr3jgJ4xS/v9EKsHAtTS7LIRuyMeSZ4pq43ynLgZcBvqY5eMFWFxVgiSYA4Rru4Z4P8Rr8FKU79tCMvjtoLqUw3JcPUl6VR2XLkJIvuJYZJ7o=
