language: php
sudo: false
cache:
  apt: true
  directories:
  - "$HOME/.composer/cache"
  - "$HOME/.cache/bin"
  - "$HOME/.n98-magerun/modules"
  - "$HOME/.cache/magento"
php:
- 7.0
- 7.1
- 7.2
matrix:
  fast_finish: true
  allow_failures:
  - php: 7.2
env:
  global:
  - APPNAME=Ffuenf_Statuschange
  - secure: lCpTeZuZK6Cw2GgZgxQNGVlpJoj/pvt2QlKlX3KM8Te7VVLGhtY8+9wvdwKqLkItuXXMB/5ZNYl0hJiG81PNMlYXv3MdOFp/IjyZcCj2Rq6TNsfnBGrQds4DE0kcUC6Srf4LIAfBPj+E8bMW+2KSE2DG9wwCvGOJFND9nYfR3Jo45BX0hRgsjdYdsfliDGIERDwsaaZDx1SpdF5iSnTpULsEvYsXBW2tC+XrFWywQJpFl5sO8Xk0yeAy+IoeuAMB4vA1QNc8KeFi7QTPeq633Uf230J/vugLtEm72A2P8Eone/XFWYbZwZ7a8hq2oq4V0SqV7oXjp0RjL7IEfRhZ9f8kjuvDoZaijQs1/8xV56FXdRjH54C+9Ep+HXX0FbC6pObWskJP/cHm/XC3hPpQ/Z7VkbZyAmzC9QZ97h91Hn6lYa1fQhQIkSmg3kt5Mpw3+ZznuK9sny16xCHTuU0h7FfSg9LJ0TKr/tPCJHww5AHKjGVFdhTxbI0K+UfFCn6GwLVJnQLGCI1mwdKaD32iDxePMxHeVKsM2M1Xd5Tgl8cyvzc1F+NDt/1i5v+MGkhVZyliNaA0zVQWbyclCEYROTbuV68HdsWgW0JXEW3PeK8vqiwF7ZSBAye/0S9Hq7e/uJ2IVxhwXKWzEzel2qCDOj5wUbc4OUS2N46sDBp4DH4=
  - secure: amo9CpYxZihLaZKtZaqx/DKxyd95oFUs7J8egVMz/evJHtvf6MczrXn9V9t9qRa3XPJ2UBMTzVP2NN/KN9+PUV68xHuxHcP3dLYN8bPFWF7n3HNXhCFUN58SF70+e6P+vn3QsElbnyIRfOIzt1U5mJPESaPGqUJNAjdleRUuuf6Ge3hnpK63qrepaUiLGWQwrIgGYpux/iV8tI2gJroHU32ljDlGdBt3N2K3iNBajSg5RITL4ED3ofZDsTuk36cOc1jShltw3+HB0+ANfp/lUlbC92ScgfYBTEgm0KVu58LtKTms3EE43Iy5AZ9fcudUgqABp/VlUmV74qN1faq0Q45xjmgbSwalHDcVCnaNR6cOEpqG9aI74pRY5WhfswbGYjIE2+0W/BJ6M4sAbBIy6aos6o/u+eO98bkjFiaOLZQH4oxm2Dyfhh+aMUsz9b6JsYnposm6CvLZvk4doaT3OXQ7tZt6UbhMbi1ZDbGp2Fxb34MWDcHzG6nZu2zOqmVpWpftMEZANx+kUbS4Iplhuxddg8VKjDy9bqxhKr/9cgyTm5ILPg8H5jRsXOKuJdh1GGorq7Q8THJwMEC8gbDupqq1vPBJcZDow02Qvw600x7Lcio1BeoA8PWlJ4jT9xNoHC51Ln1hdlROsILdcOKJAvI7PbIe6s56OXdEwPbzYgQ=
  - secure: DX2L4KmOqKJwtecxf5FGzyoC6BzxfmOVWIAHwGKZ8nw+tarJfM85gPlHg3eIWSbzXS0HkkiN2bejB2qvzdPH7YEhYlcFfoJVmcwNuH8KfRpQkc+9aoYbImW6/vEPWzuUmGfq4rZughiQ4YXN9c7mCzfWT3iMMsG14E1q5sEE0nJIWuzbhy0mzWel7+i/MWuYSMuzj5bC29lKFMiEu9iSpXaY6L17nwJDMZuIZyN8SmLBQfNN/yajbE5A8nLL7e77csy9TBUY+e8OEnZsT7hbRwSOfEnOqTORSyBxyMdMjAZbj7547iRp5t/4VFHDjMT4WlkJcyeEJIzEmJr5LTZCE1iz90vmTx9DxOy3XDZ3BsgdrNWJNx0vLav0BSeIf2c9bvmBKAwBVyCj7N+Lic3hX9Y0b82rjt7tmynPB74X0j9QsxqQFtifYRlWitVlr8+zIT0zoRiddKSxFGfJP9XnEi5HQhuOyeW8/yL6ow0AVxl++vJs+MySsunL9Kyp9xvE8BnTUkDKK7R6+GKsAyV1uPPKKkImno8jMU1AOyWpP0d2NH4Dpk1FCZ7g98oU2+PmCVGoDk3OkwP+Ujk/JTDuTQ8bnDW3OTwx24tCc4nGWuu6XooN1xPNQ/t0SG7PJKg8Kz1nqz5m97NBO00+HNfMVPJEq2DGR7OZwgBMduyJ/f8=
  matrix:
  - MAGENTO_VERSION=ce-1.9.3.10
  - MAGENTO_VERSION=ce-1.9.2.4
  - MAGENTO_VERSION=ce-1.9.1.1
before_install:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/before_install.sh
  | bash
script:
- curl -sSL https://raw.githubusercontent.com/ffuenf/MageTestStand/master/script.sh
  | bash
deploy:
  provider: releases
  file:
  - "${APPNAME}-${TRAVIS_TAG}.zip"
  - "${APPNAME}-${TRAVIS_TAG}.tar.gz"
  skip_cleanup: true
  on:
    branch: master
    tags: true
  api_key:
    secure: W+CamVLeVHqzd3d+wAdA2iJfh6EUMLVidPMQQsGy6annUlL7B/mN/JK2Z1xO22I1pHOdYG8WzK7xeDz6U8Njo2IUp+Vik5fuCSKpA50DKDMo8Bng10IlcxL5AseHoQOZcGCNhkDyOU766Rkxej3k4KUAlPbB0YLvcLy97zR29Mw0+2SXhhP56X0h1jmfdEw/kreYXup+oetb/cT/c5nEUKV1sZ/NxJZQ7OPz2L8DwMxIr3i0T3g4DvrgU+GkegrVFk4+sOvpl9AYX6uvwGVVTfhP2w+TE6murCqTyPzkLo49BxgOyVtNWXW1uUGh9cgcSJAXB2Nm7cnfJsQwXsczkM6hWd07ZKGZr/aXvGg9unsbnEJrLXbGq575nG/zy1rcXLtfbEiO6a6peNzv6poWqJw684Q62ElyTL7P+fY2tURMhoWJoeLDHf9PzgiAZjlHe2QIbDMsDUfZ1zDHnT/GznlHNXd9Urm+9p4OmSw+E29o6jteRd5i0r65IPeED8J/MoE3qeHPVCFgqkExrtUtlySWUnanJFaaSzY+EPuTCxv55Mq8Ukr54XDTORgKrp5ZQ/vI/bOIUe2CZtQTXQcdgNaGLHLMhIU1efJmkXD5mx4c3iKLBYYCgVLVp4YwiX2c5q7aZKx7tfVA17uCUV0qF7yPfqVgnw+ueRIOXSTopDA=
notifications:
  slack:
    secure: eetnYKlR51Tz6BBxHpX7c9TgQ71QMYp2RZvaH5EHtW929QSKaozum29MwFda6MggFXIa3TrbyZ/Jp/HNJsbpz2sszMB1XgwutWFZrW3wj50k3LBBPnFZnZQx0y/HDLvAvQAAUvl/W6Yahnspg4+t0EN6ihmL8nQB/CiFV4ZyniPe4gkyIOqJKtwdgkga58TwtktyoJ+heCaQBC2Fu/Y6Q8LokaoW5iSoRt436MkPcAIN3u/1gJd6OL++z4KMvjRdTdFBEIcca5pIeZYdenWUu5mcuO4XVfspkWah117PfJPn8CA5e/iatStBKDz65Wm3ywJiPgRghhv32iahT7XvLmW0xFqxwxT5J0jzKjI+aI0O9Zir/Hjp9vzp7rJ3Vh5R0Ybd/AcNtigY7q+7fOPTNysZRYTHDe9Ygh9c31BbzEBY8ikNK8GCrqKprrkXbv2FcDyA4y815Dv6S0Ti26ZWguCb8aFqyZeM6+L/rDuQztLnAdmYa9+FH9sks/xMLU4oVQtIk3OIoU9f83ZYi2sQc92LeHFasnfNO783WSjMeHGDcXbN64M3QRHe4P3dXZ8wnN/AsA4RvX7W48lMV7HKVtuA6H0B+J+Rg8mPiihq/DU0KBPDaLzH5cqt2Ycl6ui6N4WhgVNhXEKy0n81ZiExcIWCIYZDkbQk1wiVWKOKgUw=
